const LOCATION = {
    LOAD: 'LOCATION_LOAD',
    LOAD_SUCCESS: 'LOCATION_LOAD_SUCCESS',
    LOAD_FAIL: 'LOCATION_LOAD_FAIL',
    ON_MARKER_DRAGGED: 'LOCATION_MARKER_DRAGGED',
    ON_PLACE_SELECTED: 'ON_PLACE_SELECTED'
}

export {LOCATION}